### ISSUE TITLE
Could not find a declaration file for module '@evervault/react'

### ISSUE THREAD

**Issue by kaydenthomson** [evervault/evervault-react#63]
Hello!
I'm just getting started with Evervault, just installing the React SDK. Currently using Typescript and Next.js. I get the following error for a missing types declaration file.

<img width="442" alt="Screenshot 2023-06-05 at 11 02 05 PM" src="https://github.com/evervault/evervault-react/assets/9437192/47d0f384-a759-4e4b-8a3f-f4869d9cceec">

> Could not find a declaration file for module '@evervault/react'. `/node_modules/@evervault/react/build/lib/index.js` implicitly has an 'any' type.
>   Try `npm i --save-dev @types/evervault__react` if it exists or add a new declaration (.d.ts) file containing `declare module '@evervault/react';`

When attempting to install `@types/evervault__react` I receive a 404.

```
404 Not Found - GET https://registry.npmjs.org/@types%2fevervault__react - Not found
npm ERR! 404 
npm ERR! 404  '@types/evervault__react@*' is not in this registry.
```

**Comment by DogPawHat** [comment]
This has been fixed now. The typescript declarations should be in `1.2.0` on npm.
